[tool.poetry]
name = "aws-pipeline"
version = "0.1.0"
description = ""
authors = ["Hiba TOUDERTI <hibatouderti@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ansible = "^9.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
